---
name: "🐛 Bug report"
description: "Report a bug with the RiverLink SDVoE Matrix integration"
labels: ["Bug"]
body:
- type: markdown
  attributes:
    value: |
      **Thanks for reporting a bug for RiverLink SDVoE Matrix!**
      Before you open a new issue, search through [existing issues](https://github.com/switch180/RiverLink-SDVoE/issues?q=is%3Aissue+label%3A%22Bug%22+) to see if others have had the same problem.

- type: input
  attributes:
    label: "Home Assistant Version"
    description: "Find in: Settings → System → About (at the bottom) → Core version"
    placeholder: "2025.2.4"
  validations:
    required: true

- type: input
  attributes:
    label: "RiverLink SDVoE Matrix Version"
    description: "Find in: HACS → Integrations → RiverLink SDVoE Matrix → Version number shown below the title as 'Version Downloaded'"
    placeholder: "0.3.0"
  validations:
    required: true

- type: textarea
  attributes:
    label: "SDVoE System Information"
    description: "Provide details about your SDVoE hardware and network"
    placeholder: |
      - SDVoE Hardware: (e.g., Semtech BlueRiver chipset, specific transmitter/receiver models)
      - SDVoE API version:
      - Network configuration:
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the issue template completely
        required: true
      - label: This issue contains only ONE bug (open separate issues for multiple bugs)
        required: true
      - label: This is not a duplicate of [existing issues](https://github.com/switch180/RiverLink-SDVoE/issues?q=is%3Aissue+label%3A%22Bug%22+)
        required: true

- type: textarea
  attributes:
    label: "Bug Description"
    description: "A clear description of what the bug is"
    placeholder: "When I try to route Video Source A to Display B, the integration..."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Steps to Reproduce"
    description: "Detailed steps to reproduce the bug"
    value: |
      1. Go to Settings → Devices & Services → RiverLink SDVoE Matrix
      2. Select receiver device '...'
      3. Change video source to '...'
      4. Observe error: '...'
  validations:
    required: true

- type: textarea
  attributes:
    label: "Expected Behavior"
    description: "What should happen"
    placeholder: "The video source should route successfully and the display should show the new content"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Actual Behavior"
    description: "What actually happens"
    placeholder: "The integration throws an error and the routing fails"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Debug Logs"
    description: |
      Enable debug logging by adding to configuration.yaml:
      ```yaml
      logger:
        logs:
          custom_components.riverlink: debug
      ```
      Then restart HA and reproduce the issue. Paste ALL logs from startup to error.
    render: text
  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics Dump"
    description: "Drag the diagnostics file here (Settings → Devices & Services → RiverLink → 3 dots → Download Diagnostics)"
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional Context"
    description: "Screenshots, network topology diagrams, or anything else that helps"
  validations:
    required: false
